### ISSUE TITLE
I believe this no longer works, correct?

### ISSUE THREAD

**Issue by zefoo** [LouisBrunner/slack-channel-backup#3]
It looks like Slack changed their API and broke all backup scripts, can you confirm? Thank you.

**Comment by LouisBrunner** [comment]
Ah, I haven't used this in a while so I am not sure, could you give me an example with traceback/error message?

**Comment by zefoo** [comment]
Grateful for your timely response.

```
$ ./slack-backup.py team-john
Traceback (most recent call last):
  File "./slack-backup.py", line 199, in <module>
    main()
  File "./slack-backup.py", line 134, in main
    client = slack.WebClient(token=token)
AttributeError: module 'slack' has no attribute 'WebClient'
```

I've looked at a few other libraries that seems to have broke, I don't think anything works but I might be missing something here and/or misunderstood Slack's API changes. 

Are you still able to run a backup of a misc channel? Hmph. Thanks –

**Comment by LouisBrunner** [comment]
@zefoo,

I pushed a commit that pins the version of `slack` to the last working version I used.

I don't have a workspace I can use to test it anymore but it seems to be going through and trying to authenticate, so it might be working?
